// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_C.Data;

namespace Project_C.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201119132314_Yeet")]
    partial class Yeet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project_C.Data.SessionInfo", b =>
                {
                    b.Property<int>("session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("session_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("session_location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("session_name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("session_id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Project_C.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Project_C.Models.SessionConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcceptedInvites")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("SessionConfirmation");
                });

            modelBuilder.Entity("Project_C.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("accept_invitation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project_C.Models.UserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("RolesNameId")
                        .HasColumnType("int");

                    b.Property<int?>("UserNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolesNameId");

                    b.HasIndex("UserNameId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Project_C.Models.UserRoles", b =>
                {
                    b.HasOne("Project_C.Models.Roles", "RolesName")
                        .WithMany()
                        .HasForeignKey("RolesNameId");

                    b.HasOne("Project_C.Models.User", "UserName")
                        .WithMany()
                        .HasForeignKey("UserNameId");
                });
#pragma warning restore 612, 618
        }
    }
}
